// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package jobs

import (
	"context"
	"strings"
)

const deleteObsoleteJobStates = `-- name: DeleteObsoleteJobStates :exec
DELETE FROM job_state
WHERE
  job_slug NOT IN (/*SLICE:job_slugs*/?)
`

func (q *Queries) DeleteObsoleteJobStates(ctx context.Context, jobSlugs []string) error {
	query := deleteObsoleteJobStates
	var queryParams []interface{}
	if len(jobSlugs) > 0 {
		for _, v := range jobSlugs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:job_slugs*/?", strings.Repeat(",?", len(jobSlugs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:job_slugs*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getJobStates = `-- name: GetJobStates :many
SELECT
  job_slug,
  disabled
FROM
  job_state
`

func (q *Queries) GetJobStates(ctx context.Context) ([]JobState, error) {
	rows, err := q.db.QueryContext(ctx, getJobStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobState
	for rows.Next() {
		var i JobState
		if err := rows.Scan(&i.JobSlug, &i.Disabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobState = `-- name: SetJobState :exec
INSERT INTO
  job_state (job_slug, disabled)
VALUES
  (?, ?) ON CONFLICT (job_slug) DO
UPDATE
SET
  disabled = excluded.disabled
`

type SetJobStateParams struct {
	JobSlug  string `json:"job_slug"`
	Disabled int64  `json:"disabled"`
}

func (q *Queries) SetJobState(ctx context.Context, arg SetJobStateParams) error {
	_, err := q.db.ExecContext(ctx, setJobState, arg.JobSlug, arg.Disabled)
	return err
}
